[project]
name = "better-google-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.9"
dependencies = [
    "faster-whisper>=1.2.1",
    "laya[onnx]>=0.3.24",
    "mlx-whisper>=0.4.3",
    "python-stopwatch>=1.1.11",
    "pywhispercpp>=1.5.1",
    "silero-vad[audio]>=6.2.3",
    "sounddevice>=0.5.6",
]
